### ISSUE TITLE
Add a license 

### ISSUE THREAD

**Issue by OlivierJM** [devconzm/devconzm19#7]
For a project to be fully opensource it should have a license that matches the opensource standards like MIT or Apache. 

Kindly check [here](https://github.com/devconzm/devconzm19/community/license/new?branch=master) for a list of licenses then we can add one

**Comment by malgamves** [comment]
I feel MIT is the best fir for us

**Comment by OlivierJM** [comment]
I will go ahead and add MIT license

**Comment by OlivierJM** [comment]
I will go ahead and close this, feel free to re-open if there is need.
